lavalink:
    plugins:
        - dependency: com.github.topi314.lavasrc:lavasrc-plugin:4.4.1
        - dependency: com.github.topi314.lavasearch:lavasearch-plugin:1.0.0
        - dependency: dev.lavalink.youtube:youtube-plugin:1.11.4
          snapshot: false
    server:
        bufferDurationMs: 400
        filters:
            channelMix: true
            distortion: true
            equalizer: true
            karaoke: true
            lowPass: true
            rotation: true
            timescale: true
            tremolo: true
            vibrato: true
            volume: true
        frameBufferDurationMs: 5000
        gc-warnings: true
        nonAllocatingFrameBuffer: false
        opusEncodingQuality: 10
        password: root
        playerUpdateInterval: 5
        resamplingQuality: LOW
        soundcloudSearchEnabled: true
        sources:
            bandcamp: true
            http: true
            local: false
            nico: true
            soundcloud: true
            twitch: true
            vimeo: true
            youtube: false
        trackStuckThresholdMs: 10000
        useSeekGhosting: true
        youtubeConfig:
            email: the.skully100@gmail.com
            password: '@Kevin9069'
        youtubePlaylistLoadLimit: 6
        youtubeSearchEnabled: true
logging:
    file:
        path: ./logs/
    level:
        lavalink: INFO
        root: INFO
    logback:
        rollingpolicy:
            max-file-size: 1GB
            max-history: 30
    request:
        enabled: true
        includeClientInfo: true
        includeHeaders: false
        includePayload: true
        includeQueryString: true
        maxPayloadLength: 10000
metrics:
    prometheus:
        enabled: false
        endpoint: /metrics
plugins:
    lavasrc:
        applemusic:
            albumLoadLimit: 6
            countryCode: US
            keyID: your key id
            mediaAPIToken: your apple music api token
            musicKitKey: "-----BEGIN PRIVATE KEY-----\nyour key\n-----END PRIVATE KEY-----      \n"
            playlistLoadLimit: 6
            teamID: your team id
        deezer:
            formats:
                - FLAC
                - MP3_320
                - MP3_256
                - MP3_128
                - MP3_64
                - AAC_64
            masterDecryptionKey: your master decryption key
        flowerytts:
            audioFormat: mp3
            silence: 0
            speed: 1
            translate: false
            voice: 4ba7bd1b-cb5f-5c3f-9e1c-9ee8be2b0bdd
        lyrics-sources:
            deezer: false
            spotify: true
            vkmusic: false
            yandexmusic: false
            youtube: true
        providers:
            - ytsearch:"%ISRC%"
            - ytsearch:%QUERY%
            - scsearch:%QUERY%
        sources:
            applemusic: false
            deezer: false
            flowerytts: true
            spotify: true
            vkmusic: false
            yandexmusic: false
            youtube: true
        spotify:
            albumLoadLimit: 6
            clientId: b02cbb2c4254416897bdbe60fc9bba34
            clientSecret: f452d527e65c45488c75734b7f2208d8
            countryCode: IN
            localFiles: false
            playlistLoadLimit: 6
            resolveArtistsInSearch: true
        vkmusic:
            artistLoadLimit: 1
            playlistLoadLimit: 1
            recommendationsLoadLimit: 10
            userToken: your user token
        yandexmusic:
            accessToken: your access token
            albumLoadLimit: 1
            artistLoadLimit: 1
            playlistLoadLimit: 1
        youtube:
            albumLoadLimit: 1
            artistLoadLimit: 1
            countryCode: IN
            playlistLoadLimit: 1
    youtube:
        ANDROID_MUSIC:
            playback: true
            playlistLoading: false
            searching: true
            videoLoading: true
        MUSIC:
            playback: false
            playlistLoading: false
            searching: true
            videoLoading: true
        TV:
            playback: true
            playlistLoading: false
            searching: false
            videoLoading: false
        TVHTML5EMBEDDED:
            playback: true
            playlistLoading: false
            searching: false
            videoLoading: false
        WEB:
            playback: true
            playlistLoading: false
            searching: true
            videoLoading: true
        WEBEMBEDDED:
            playback: true
            playlistLoading: false
            searching: false
            videoLoading: false
        allowDirectPlaylistIds: true
        allowDirectVideoIds: true
        allowSearch: true
        clients:
            - ANDROID_MUSIC
            - MUSIC
            - WEB
            - WEBEMBEDDED
            - TVHTML5EMBEDDED
            - TV
        enabled: true
        oauth:
            enabled: true
            refreshToken: 1//0gWPu_BKm15u9CgYIARAAGBASNwF-L9Ir4WUmQMJCcEryMZ0KvVbyVJAsmYlqinsX_1PruXFDi3p0FPh_2i3TjyLhd4UA8wDniBE
sentry:
    dsn: ""
    environment: ""
server:
    address: 0.0.0.0
    http2:
        enabled: false
    port: 1092
